apiVersion: v1
kind: PersistentVolume
metadata: 
    namespace: ns-dev-web 
    name: pv1
spec:
    capacity:
        storage: 1Gi
    accessModes:
        -   ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
        path: /root/nfs_root/test/www
        server: 192.168.8.123

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
    namespace: ns-dev-web 
    name: pvc1
spec:
    accessModes:
        -   ReadWriteOnce
    resources:
        requests:
            storage: 500Mi